class PortServices:
    def __init__(self, host_port: int):
        self.host_port = host_port

    def get_port_service(self) -> str:
        ports_service = {
            7: "Echo",
            19: "CHARGEN",
            20: "FTP-data",
            21: "FTP",
            22: "SSH/SCP/SFTP",
            23: "Telnet",
            25: "SMTP",
            42: "WINS Replication",
            43: "WHOIS",
            49: "TACACS",
            53: "DNS",
            67: "DHCP/BOOTP Server",
            68: "DHCP/BOOTP Client",
            69: "TFTP",
            70: "Gopher",
            79: "Finger",
            80: "HTTP",
            81: "hosts2-ns",
            88: "Kerberos",
            102: "Microsoft Exchange ISO-TSAP",
            110: "POP3",
            123: "NTP",
            135: "Windows RPC",
            137: "NetBIOS Name Service",
            138: "NetBIOS Datagram Service",
            139: "NetBIOS Session Service",
            143: "IMAP",
            161: "SNMP",
            162: "SNMP Trap",
            179: "BGP",
            389: "LDAP",
            443: "HTTPS",
            445: "Server Message Block (SMB)",
            465: "SMTPS",
            514: "Syslog",
            636: "LDAPS",
            989: "FTPS Data",
            990: "FTPS Control",
            993: "IMAPS",
            995: "POP3S",
            1433: "MS SQL Server",
            1701: "L2TP",
            1723: "PPTP",
            1812: "RADIUS Authentication",
            1813: "RADIUS Accounting",
            3306: "MySQL",
            3389: "RDP",
            5060: "SIP",
            5061: "SIPS",
            5190: "ICQ and AOL Instant Messenger",
            5222: "XMPP Client Connection",
            5223: "Apple Push Notification Service",
            5900: "VNC",
            6667: "IRC",
            8000: "iRDMI (Intel Remote Desktop Management Interface)",
            8080: "HTTP Alternate",
            8443: "HTTPS Alternate",
            8888: "NewsEDGE server",
            49152: "Dynamic/Private Ports Start",
            65535: "Dynamic/Private Ports End"
        }

        if self.host_port in ports_service:
            return ports_service[self.host_port]
